---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-14.04-i386
  - name: centos-7.1
  - name: debian-7.8
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[apktool::default]
    attributes:
